packages:
  - apps/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - lmdb
  - msgpackr-extract
  - prisma

publicHoistPattern:
  - esbuild
  - typescript
  - dotenv
